stages:
    - build
    - deploy

before_script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - docker info

build_image:
  stage: build
  script:
    - docker build -t systemli-website:v1 .

deploy_prod:
  stage: deploy
  only:
    - master
  script:
    - docker run --rm -v $PWD:/srv/jekyll -u $(id -u):$(id -g) systemli-website:v1
    - rsync -vrltgoDz --delete -e "ssh -p22" ./_site/ systemli@www3.systemli.org:/var/www/www.systemli.org/www
    - rm -rf _site/

deploy_staging:
  stage: deploy
  only:
    - staging
  script:
    - docker run --rm -v $PWD:/srv/jekyll -u $(id -u):$(id -g) systemli-website:v1
    - rsync -vrltgoDz --delete -e "ssh -p22" ./_site/ systemli-staging@www3.systemli.org:/var/www/www.staging.systemli.org/www
    - rm -rf _site/
