baseURL = "https://www.systemli.org"
languageCode = "de"
title = "Systemli - Your friendly tech collective"
theme = "systemli"
Paginate = 4
sectionPagesMenu = "main"

[params]
    favicon = "favicon.ico"
